name: flutter_application_1
description: "Imc "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  carousel_slider: ^5.1.1
  intl: ^0.18.1
  logger: ^2.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  lottie: ^3.1.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.0
  http: ^1.5.0
  url_launcher: ^6.3.0
  email_otp: ^3.0.2
  firebase_storage: ^12.3.4
<<<<<<< HEAD
  flutter_dotenv: ^5.0.2
dependency_overrides:
  carousel_slider: 5.1.1
=======
>>>>>>> feature/stabilize-before-main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/carousel/
    - assets/images/emotions/
    - assets/images/flores/
    - assets/images/diario/
    - assets/images/ia/
    - assets/images/icon/
    - assets/images/metas/
    - assets/animations/
    # Explicitly list the Lottie file to avoid any asset resolution issues
    - assets/animations/flower.json
    - assets/env/
    - assets/env/.env
